---

- name: reload systemctl
  become: yes
  become_user: "{{ container_run_as_user }}"
  systemd:
    scope: "{{ service_scope }}"
    daemon_reload: yes

- name: start service
  become: yes
  become_user: "{{ container_run_as_user }}"
  systemd:
    scope: "{{ service_scope }}"
    name: "{{ service_name }}"
    state: started

- name: restart service
  become: yes
  become_user: "{{ container_run_as_user }}"
  systemd:
    scope: "{{ service_scope }}"
    name: "{{ service_name }}"
    state: restarted
